In [48]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/mohammadhafees/ibm-amlsim-100k-accounts-10m-transactions/100Kvertices-10Medges/accounts.csv
/kaggle/input/datasets/mohammadhafees/ibm-amlsim-100k-accounts-10m-transactions/100Kvertices-10Medges/alerts.csv
/kaggle/input/datasets/mohammadhafees/ibm-amlsim-100k-accounts-10m-transactions/100Kvertices-10Medges/transactions.csv
/kaggle/input/datasets/mohammadhafees/ibm-amlsim-100k-accounts-10m-transactions/100Kvertices-10Medges/paramFiles/alertPatterns.csv
/kaggle/input/datasets/mohammadhafees/ibm-amlsim-100k-accounts-10m-transactions/100Kvertices-10Medges/paramFiles/degree.csv
/kaggle/input/datasets/mohammadhafees/ibm-amlsim-100k-accounts-10m-transactions/100Kvertices-10Medges/paramFiles/accounts.csv
/kaggle/input/datasets/mohammadhafees/ibm-amlsim-100k-accounts-10m-transactions/100Kvertices-10Medges/paramFiles/transactionType.csv
/kaggle/input/datasets/mohammadhafees/ibm-amlsim-100k-accounts-10m-transactions/100Kvertices-10Medges/stat/cc.png
/kaggle/input/datasets/mohammadhafees/ibm-amlsim-100k-accounts-10m-transactions/100Kvertices-10Medges/stat/deg.png
/kaggle/input/datasets/mohammadhafees/ibm-amlsim-100k-accounts-10m-transactions/100Kvertices-10Medges/stat/alert.png
/kaggle/input/datasets/mohammadhafees/ibm-amlsim-100k-accounts-10m-transactions/100Kvertices-10Medges/stat/diameter.png
/kaggle/input/datasets/mohammadhafees/ibm-amlsim-100k-accounts-10m-transactions/100Kvertices-10Medges/stat/wcc.png
/kaggle/input/datasets/mohammadhafees/ibm-amlsim-100k-accounts-10m-transactions/100Kvertices-10Medges/stat/count.png

In [49]:
df=pd.read_csv('/kaggle/input/datasets/mohammadhafees/ibm-amlsim-100k-accounts-10m-transactions/100Kvertices-10Medges/transactions.csv', nrows=100_000)
df.head()

,TX_ID,SENDER_ACCOUNT_ID,RECEIVER_ACCOUNT_ID,TX_TYPE,TX_AMOUNT,TIMESTAMP,IS_FRAUD,ALERT_ID
0,1,5942,92982,TRANSFER,516.95,0,False,-1
1,2,86700,43995,TRANSFER,197.88,0,False,-1
2,3,86700,95516,TRANSFER,197.88,0,False,-1
3,4,86700,83911,TRANSFER,197.88,0,False,-1
4,5,86700,82801,TRANSFER,197.88,0,False,-1

In [50]:
df.drop(columns = ['TX_ID','TX_TYPE','ALERT_ID'],inplace=True)
df.head()

   SENDER_ACCOUNT_ID  RECEIVER_ACCOUNT_ID  TX_AMOUNT  TIMESTAMP  IS_FRAUD
0               5942                92982     516.95          0     False
1              86700                43995     197.88          0     False
2              86700                95516     197.88          0     False
3              86700                83911     197.88          0     False
4              86700                82801     197.88          0     False

In [51]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 5 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   SENDER_ACCOUNT_ID    100000 non-null  int64
 1   RECEIVER_ACCOUNT_ID  100000 non-null  int64
 2   TX_AMOUNT            100000 non-null  float64
 3   TIMESTAMP            100000 non-null  int64
 4   IS_FRAUD             100000 non-null  bool
dtypes: bool(1), float64(1), int64(3)
memory usage: 3.1 MB

In [52]:
X = df[['SENDER_ACCOUNT_ID','RECEIVER_ACCOUNT_ID','TX_AMOUNT','TIMESTAMP']].copy()
y = df['IS_FRAUD'].astype(int)

In [53]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [54]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

X_train_trf = scaler.fit_transform(X_train)
X_test_trf = scaler.transform(X_test)

In [55]:

from sklearn.utils.class_weight import compute_class_weight
import numpy as np

classes = np.array([0, 1])

weights = compute_class_weight(
    class_weight='balanced',
    classes=classes,
    y=y_train
)

class_weights = {
    0: weights[0],
    1: weights[1]
}

print(class_weights)

{0: np.float64(0.5007636645884974), 1: np.float64(327.8688524590164)}

In [56]:
import tensorflow 
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

In [57]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Input

model = Sequential([
    Input(shape=(4,)),
    Dense(16, activation='relu'),
    Dense(8, activation='relu'),
    Dense(1, activation='sigmoid')
])

In [58]:
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_9 (Dense)                 │ (None, 16)             │            80 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_10 (Dense)                │ (None, 8)              │           136 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_11 (Dense)                │ (None, 1)              │             9 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 225 (900.00 B)

 Trainable params: 225 (900.00 B)

 Non-trainable params: 0 (0.00 B)

In [59]:
model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

In [60]:
history = model.fit(X_train_trf,y_train,batch_size=50,epochs=100,verbose=1,validation_split=0.2,class_weight=class_weights)

Epoch 1/100
1280/1280 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.8993 - loss: 0.6632 - val_accuracy: 0.7089 - val_loss: 0.4316
Epoch 2/100
1280/1280 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.6775 - loss: 0.4863 - val_accuracy: 0.6653 - val_loss: 0.4723
Epoch 3/100
1280/1280 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - accuracy: 0.6774 - loss: 0.4258 - val_accuracy: 0.6697 - val_loss: 0.4794
Epoch 4/100
1280/1280 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.6782 - loss: 0.3999 - val_accuracy: 0.6797 - val_loss: 0.4741
Epoch 5/100
1280/1280 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.6891 - loss: 0.3889 - val_accuracy: 0.6705 - val_loss: 0.5164
Epoch 6/100
1280/1280 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.6846 - loss: 0.3873 - val_accuracy: 0.6764 - val_loss: 0.4986
Epoch 7/100
1280/1280 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.6811 - loss: 0.3826 - val_accuracy: 0.6832 - val_loss: 0.4655
Epoch 8/100
1280/1280 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.6866 - loss: 0.3767 - val_accuracy: 0.6941 - val_loss: 0.3855
Epoch 9/100
1280/1280 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.6849 - loss: 0.3775 - val_accuracy: 0.6796 - val_loss: 0.4231
Epoch 10/100
1280/1280 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.6853 - loss: 0.3764 - val_accuracy: 0.6688 - val_loss: 0.5290
Epoch 11/100
1280/1280 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.6853 - loss: 0.3751 - val_accuracy: 0.6774 - val_loss: 0.4706
Epoch 12/100
1280/1280 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.6940 - loss: 0.3699 - val_accuracy: 0.6911 - val_loss: 0.4894
Epoch 13/100
1280/1280 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.6880 - loss: 0.3732 - val_accuracy: 0.6711 - val_loss: 0.4966
Epoch 14/100
1280/1280 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.6844 - loss: 0.3728 - val_accuracy: 0.6707 - val_loss: 0.5254
Epoch 15/100
1280/1280 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.6897 - loss: 0.3691 - val_accuracy: 0.6798 - val_loss: 0.4833
Epoch 16/100
1280/1280 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.6870 - loss: 0.3732 - val_accuracy: 0.6808 - val_loss: 0.4417
Epoch 17/100
1280/1280 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.6980 - loss: 0.3650 - val_accuracy: 0.6932 - val_loss: 0.4338
Epoch 18/100
1280/1280 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.6932 - loss: 0.3727 - val_accuracy: 0.6726 - val_loss: 0.5234
Epoch 19/100
1280/1280 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.6921 - loss: 0.3673 - val_accuracy: 0.6891 - val_loss: 0.4428
Epoch 20/100
1280/1280 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.6982 - loss: 0.3663 - val_accuracy: 0.6911 - val_loss: 0.4501
Epoch 21/100
1280/1280 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.6948 - loss: 0.3707 - val_accuracy: 0.6847 - val_loss: 0.4508
Epoch 22/100
1280/1280 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.6921 - loss: 0.3646 - val_accuracy: 0.6999 - val_loss: 0.4089
Epoch 23/100
1280/1280 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.6962 - loss: 0.3663 - val_accuracy: 0.6939 - val_loss: 0.4228
Epoch 24/100
1280/1280 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.6976 - loss: 0.3656 - val_accuracy: 0.6820 - val_loss: 0.4745
Epoch 25/100
1280/1280 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.6896 - loss: 0.3673 - val_accuracy: 0.6733 - val_loss: 0.5040
Epoch 26/100
1280/1280 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.6917 - loss: 0.3669 - val_accuracy: 0.6964 - val_loss: 0.4372
Epoch 27/100
1280/1280 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.6977 - loss: 0.3633 - val_accuracy: 0.6702 - val_loss: 0.5334
Epoch 28/100
1280/1280 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.6854 - loss: 0.3662 - val_accuracy: 0.6822 - val_loss: 0.4490
Epoch 29/100
1280/1280 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.6972 - loss: 0.3648 - val_accuracy: 0.6761 - val_loss: 0.4448
Epoch 30/100
1280/1280 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.6974 - loss: 0.3658 - val_accuracy: 0.6829 - val_loss: 0.4475
Epoch 31/100
1280/1280 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.6982 - loss: 0.3614 - val_accuracy: 0.6936 - val_loss: 0.4489
Epoch 32/100
1280/1280 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.6953 - loss: 0.3641 - val_accuracy: 0.6760 - val_loss: 0.4709
Epoch 33/100
1280/1280 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.6948 - loss: 0.3620 - val_accuracy: 0.7005 - val_loss: 0.4283
Epoch 34/100
1280/1280 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.6991 - loss: 0.3605 - val_accuracy: 0.6893 - val_loss: 0.4583
Epoch 35/100
1280/1280 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7034 - loss: 0.3635 - val_accuracy: 0.6818 - val_loss: 0.4988
Epoch 36/100
1280/1280 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.6975 - loss: 0.3625 - val_accuracy: 0.7003 - val_loss: 0.4433
Epoch 37/100
1280/1280 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7024 - loss: 0.3637 - val_accuracy: 0.6756 - val_loss: 0.5257
Epoch 38/100
1280/1280 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.6924 - loss: 0.3614 - val_accuracy: 0.6859 - val_loss: 0.4668
Epoch 39/100
1280/1280 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.6987 - loss: 0.3657 - val_accuracy: 0.6793 - val_loss: 0.5058
Epoch 40/100
1280/1280 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7002 - loss: 0.3592 - val_accuracy: 0.6845 - val_loss: 0.4722
Epoch 41/100
1280/1280 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7038 - loss: 0.3611 - val_accuracy: 0.7073 - val_loss: 0.4200
Epoch 42/100
1280/1280 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7027 - loss: 0.3569 - val_accuracy: 0.6867 - val_loss: 0.4667
Epoch 43/100
1280/1280 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.6966 - loss: 0.3630 - val_accuracy: 0.6869 - val_loss: 0.4517
Epoch 44/100
1280/1280 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.6954 - loss: 0.3590 - val_accuracy: 0.6854 - val_loss: 0.4486
Epoch 45/100
1280/1280 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7218 - loss: 0.3538 - val_accuracy: 0.6962 - val_loss: 0.4531
Epoch 46/100
1280/1280 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7019 - loss: 0.3561 - val_accuracy: 0.7151 - val_loss: 0.4171
Epoch 47/100
1280/1280 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7084 - loss: 0.3610 - val_accuracy: 0.6829 - val_loss: 0.5021
Epoch 48/100
1280/1280 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7047 - loss: 0.3612 - val_accuracy: 0.6770 - val_loss: 0.5154
Epoch 49/100
1280/1280 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7080 - loss: 0.3565 - val_accuracy: 0.6851 - val_loss: 0.4977
Epoch 50/100
1280/1280 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7051 - loss: 0.3534 - val_accuracy: 0.6932 - val_loss: 0.4474
Epoch 51/100
1280/1280 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7059 - loss: 0.3603 - val_accuracy: 0.6877 - val_loss: 0.4797
Epoch 52/100
1280/1280 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7019 - loss: 0.3540 - val_accuracy: 0.7059 - val_loss: 0.3950
Epoch 53/100
1280/1280 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7128 - loss: 0.3593 - val_accuracy: 0.6870 - val_loss: 0.4760
Epoch 54/100
1280/1280 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7079 - loss: 0.3530 - val_accuracy: 0.6939 - val_loss: 0.4724
Epoch 55/100
1280/1280 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7035 - loss: 0.3543 - val_accuracy: 0.7003 - val_loss: 0.4488
Epoch 56/100
1280/1280 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7078 - loss: 0.3588 - val_accuracy: 0.6852 - val_loss: 0.4775
Epoch 57/100
1280/1280 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7137 - loss: 0.3494 - val_accuracy: 0.6802 - val_loss: 0.5316
Epoch 58/100
1280/1280 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7035 - loss: 0.3569 - val_accuracy: 0.7073 - val_loss: 0.4254
Epoch 59/100
1280/1280 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7161 - loss: 0.3544 - val_accuracy: 0.7111 - val_loss: 0.4349
Epoch 60/100
1280/1280 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7163 - loss: 0.3535 - val_accuracy: 0.6886 - val_loss: 0.4914
Epoch 61/100
1280/1280 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7081 - loss: 0.3500 - val_accuracy: 0.7017 - val_loss: 0.4306
Epoch 62/100
1280/1280 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7113 - loss: 0.3478 - val_accuracy: 0.6921 - val_loss: 0.4791
Epoch 63/100
1280/1280 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.6960 - loss: 0.3739 - val_accuracy: 0.6886 - val_loss: 0.4149
Epoch 64/100
1280/1280 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7118 - loss: 0.3514 - val_accuracy: 0.6759 - val_loss: 0.5410
Epoch 65/100
1280/1280 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7121 - loss: 0.3559 - val_accuracy: 0.6867 - val_loss: 0.4792
Epoch 66/100
1280/1280 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7204 - loss: 0.3520 - val_accuracy: 0.6811 - val_loss: 0.5506
Epoch 67/100
1280/1280 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7050 - loss: 0.3518 - val_accuracy: 0.7084 - val_loss: 0.4329
Epoch 68/100
1280/1280 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7212 - loss: 0.3639 - val_accuracy: 0.6751 - val_loss: 0.5770
Epoch 69/100
1280/1280 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7023 - loss: 0.3529 - val_accuracy: 0.6845 - val_loss: 0.4851
Epoch 70/100
1280/1280 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7201 - loss: 0.3467 - val_accuracy: 0.7818 - val_loss: 0.3289
Epoch 71/100
1280/1280 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7233 - loss: 0.3550 - val_accuracy: 0.7360 - val_loss: 0.3905
Epoch 72/100
1280/1280 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7228 - loss: 0.3527 - val_accuracy: 0.6993 - val_loss: 0.4662
Epoch 73/100
1280/1280 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7199 - loss: 0.3489 - val_accuracy: 0.7208 - val_loss: 0.4223
Epoch 74/100
1280/1280 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7087 - loss: 0.3509 - val_accuracy: 0.6897 - val_loss: 0.4954
Epoch 75/100
1280/1280 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7153 - loss: 0.3490 - val_accuracy: 0.6970 - val_loss: 0.5192
Epoch 76/100
1280/1280 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7209 - loss: 0.3464 - val_accuracy: 0.7126 - val_loss: 0.4650
Epoch 77/100
1280/1280 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7145 - loss: 0.3507 - val_accuracy: 0.6966 - val_loss: 0.4431
Epoch 78/100
1280/1280 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7174 - loss: 0.3479 - val_accuracy: 0.7093 - val_loss: 0.4199
Epoch 79/100
1280/1280 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7062 - loss: 0.3509 - val_accuracy: 0.6894 - val_loss: 0.4268
Epoch 80/100
1280/1280 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7116 - loss: 0.3503 - val_accuracy: 0.6977 - val_loss: 0.4638
Epoch 81/100
1280/1280 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7209 - loss: 0.3436 - val_accuracy: 0.7017 - val_loss: 0.4611
Epoch 82/100
1280/1280 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7155 - loss: 0.3454 - val_accuracy: 0.6942 - val_loss: 0.5038
Epoch 83/100
1280/1280 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7131 - loss: 0.3548 - val_accuracy: 0.6885 - val_loss: 0.4831
Epoch 84/100
1280/1280 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7085 - loss: 0.3470 - val_accuracy: 0.6972 - val_loss: 0.4747
Epoch 85/100
1280/1280 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7142 - loss: 0.3465 - val_accuracy: 0.6989 - val_loss: 0.4555
Epoch 86/100
1280/1280 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7172 - loss: 0.3554 - val_accuracy: 0.7113 - val_loss: 0.4274
Epoch 87/100
1280/1280 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7151 - loss: 0.3484 - val_accuracy: 0.7251 - val_loss: 0.4074
Epoch 88/100
1280/1280 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7119 - loss: 0.3494 - val_accuracy: 0.6931 - val_loss: 0.4988
Epoch 89/100
1280/1280 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7173 - loss: 0.3543 - val_accuracy: 0.6902 - val_loss: 0.4858
Epoch 90/100
1280/1280 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7222 - loss: 0.3428 - val_accuracy: 0.6953 - val_loss: 0.5278
Epoch 91/100
1280/1280 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7239 - loss: 0.3556 - val_accuracy: 0.6824 - val_loss: 0.5452
Epoch 92/100
1280/1280 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7137 - loss: 0.3468 - val_accuracy: 0.7757 - val_loss: 0.3143
Epoch 93/100
1280/1280 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7221 - loss: 0.3501 - val_accuracy: 0.7104 - val_loss: 0.4083
Epoch 94/100
1280/1280 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7150 - loss: 0.3435 - val_accuracy: 0.7001 - val_loss: 0.4757
Epoch 95/100
1280/1280 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7101 - loss: 0.3512 - val_accuracy: 0.6996 - val_loss: 0.4544
Epoch 96/100
1280/1280 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7163 - loss: 0.3458 - val_accuracy: 0.7484 - val_loss: 0.3612
Epoch 97/100
1280/1280 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7166 - loss: 0.3455 - val_accuracy: 0.7179 - val_loss: 0.3743
Epoch 98/100
1280/1280 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7161 - loss: 0.3510 - val_accuracy: 0.7117 - val_loss: 0.4111
Epoch 99/100
1280/1280 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7346 - loss: 0.3462 - val_accuracy: 0.6944 - val_loss: 0.5190
Epoch 100/100
1280/1280 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7233 - loss: 0.3434 - val_accuracy: 0.7172 - val_loss: 0.4132

In [61]:
y_prob = model.predict(X_test_trf)

625/625 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step

In [62]:
y_prob

array([[1.2381811e-27],
       [1.3808796e-09],
       [8.0995232e-01],
       ...,
       [1.1799178e-12],
       [1.6298140e-08],
       [7.8222585e-01]], dtype=float32)

In [63]:
y_pred = (y_prob >= 0.5).astype(int)
y_pred

array([[0],
       [0],
       [1],
       ...,
       [0],
       [0],
       [1]])

In [64]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

print("Accuracy score:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

Accuracy score: 0.72475
              precision    recall  f1-score   support

           0       1.00      0.72      0.84     19978
           1       0.00      1.00      0.01        22

    accuracy                           0.72     20000
   macro avg       0.50      0.86      0.42     20000
weighted avg       1.00      0.72      0.84     20000

[[14473  5505]
 [    0    22]]